name: Client CI

on: [push, pull_request]

jobs:
  Client:
    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: npm packages cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm build
          
      - name: Production Deploy
        if: github.ref == 'refs/heads/master'
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: bc441c4c-c2d9-4992-b3a2-8eef299c4b11
          NETLIFY_BASE: client
          NETLIFY_CMD: CI=false npm run build
          NETLIFY_DIR: client/build
      
      - name: Production Deploy
        if: github.ref == 'refs/heads/master'
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: bc441c4c-c2d9-4992-b3a2-8eef299c4b11
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_SITE_ID"]'