name: CI

on: [push, pull_request]

jobs:
  
  server:
    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Go
        uses: actions/setup-go@v2
        
      - name: Go modules Caching
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Test
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
        run: go test ./...
          
      - name: Production Deploy
        if: github.ref == 'refs/heads/master'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'walletvisor'
          heroku_email: 'cobogue@gmail.com'
          appdir: "server"
        env:
          HD_SECRET: ${{secrets.SECRET}}
          HD_TOKEN_EXPIRES: ${{secrets.TOKEN_EXPIRES}}
          HD_REFRESH_TOKEN_EXPIRES: ${{secrets.REFRESH_TOKEN_EXPIRES}}
