name: CI

on: [push, pull_request]

jobs:
  Server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wv-server

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Go
        uses: actions/setup-go@v2
        
      - name: Go modules Caching
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Test
        env:
          JWT_SECRET: FAKESECRET
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable
          REQUEST_LOGGER: false
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -u github.com/schrej/godacov
          go test ./tests -coverpkg "./..." -coverprofile cover.out
          godacov -t ${{secrets.CODACY_PROJECT_TOKEN}} -r ./cover.out -c ${{ github.sha }}

      - name: Development Deploy
        if: github.ref == 'refs/heads/develop'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'walletvisor-dev'
          heroku_email: 'cobogue@gmail.com'
          appdir: "wv-server"
          
      - name: Production Deploy
        if: github.ref == 'refs/heads/master'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'walletvisor'
          heroku_email: 'cobogue@gmail.com'
          appdir: "wv-server"


  Client:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: wv-client

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: npm packages cache
          uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-

        - name: Install Packages and Build
          run: |
            npm install
            npm run-script build

        #- name: Test
        #  run: npm test

        - name: Development Deploy
          if: github.ref == 'refs/heads/develop'
          uses: netlify/actions/cli@master
          env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DEV }}
            REACT_APP_API_URL: ${{ secrets.NETLIFY_SERVER_URL_DEV }}
            REACT_APP_LOGGER_LEVEL: info
            REACT_APP_LOGGER_RENDERING: true
          with:
            args: REACT_APP_API_URL=test deploy --dir=wv-client/build --prod
        
        - name: Production Deploy
          if: github.ref == 'refs/heads/master'
          uses: netlify/actions/cli@master
          env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_PROD }}
            REACT_APP_API_URL: ${{ secrets.NETLIFY_SERVER_URL_PROD }}
            REACT_APP_LOGGER_LEVEL: error
            REACT_APP_LOGGER_RENDERING: false
          with:
            args: deploy --dir=wv-client/build --prod