name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build
        run: echo Building
      
      - name: Build
        env:
          TEST: Test ENV
        run: |
          echo TEST,
          echo OK